services:
  - type: web
    name: trackruit-ml
    env: python
    plan: free
    rootDirectory: ML
    buildCommand: "./build.sh"
    startCommand: "./start.sh"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: HOST
        value: "0.0.0.0"
      - key: PORT
        value: "8000"
      - key: DEBUG
        value: "false"
      - key: LOG_LEVEL
        value: "info"
      - key: API_KEY
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: NLTK_DATA
        value: "./nltk_data"
      - key: ENABLE_SBERT
        value: "false"
      - key: ENABLE_CACHE
        value: "false"